#
# Copyright 2025 Tabs Data Inc.
#

[book]
authors = ["Tabs Data Inc."]
language = "en"
multilingual = false
src = "src"
title = "Tabsdata Examples Guide"

[preprocessor.image-size]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["./theme/custom.css"]