#
# Copyright 2025 Tabs Data Inc.
#

[tasks.failure]
plugin = "td-task-tracker"
category = "90 - Lifecycle"
description = "Handle make errors"
private = false
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    os_family = os_family
    if eq ${os_family} "windows"
        cm_run_task failure_windows
    else
        if eq ${os_family} "mac"
            cm_run_task failure_mac
        else
            if eq ${os_family} "linux"
                cm_run_task failure_linux
            end
        end
    end
    ''']

[tasks.failure_windows]
plugin = "td-task-tracker"
category = "90 - Lifecycle"
private = true
ignore_errors = true
env = { MAKE_SUCCESS = "false" }

[tasks.failure_linux]
plugin = "td-task-tracker"
category = "90 - Lifecycle"
private = true
ignore_errors = true
env = { MAKE_SUCCESS = "false" }

[tasks.failure_mac]
plugin = "td-task-tracker"
category = "90 - Lifecycle"
private = true
ignore_errors = true
env = { MAKE_SUCCESS = "false" }
script = [
    '''
    if [[ -z "$PROJECT_TABSDATA_ROOT_FOLDER" || ! -d "$PROJECT_TABSDATA_ROOT_FOLDER" ]]; then
        TD_ROOT="."
    else
        TD_ROOT="$PROJECT_TABSDATA_ROOT_FOLDER"
    fi

    if command -v viu &> /dev/null; then
        echo
        viu --width 32 ${TD_ROOT}/make/make-os/resources/images/ferri-sad.png
    fi
    if command -v lolcat &> /dev/null && command -v figlet &> /dev/null; then
        echo
        figlet -f ${TD_ROOT}/make/make-os/resources/fonts/3d.flf Failed! | lolcat
        echo
    else
        echo "⭕️ Ko!"
    fi
    ''']
