#
# Copyright 2025 Tabs Data Inc.
#

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(process)d - %(name)s - %(levelname)s - %(message)s"

handlers:

  log_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: td.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  filelock:
    level: WARNING
    propagate: False

root:
  level: DEBUG
  handlers: [log_file_handler]
