#
# Copyright 2025 Tabs Data Inc.
#

[tasks.__os__format_rs_macros]
plugin = "td-task-tracker"
category = "09 - Repair"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ cargo fmt --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML} --all"
    exec --fail-on-error cargo fmt --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML} --all
    ''']

[tasks.__os__format_rs_modules]
plugin = "td-task-tracker"
category = "09 - Repair"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ cargo fmt --manifest-path ${PROJECT_RS_TD_TABSDATA_CARGO_TOML} --all"
    exec --fail-on-error cargo fmt --manifest-path ${PROJECT_RS_TD_TABSDATA_CARGO_TOML} --all
    ''']

[tasks.__os__format_rs_expansions]
plugin = "td-task-tracker"
category = "09 - Repair"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ cargo fmt --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML} --all"
    exec --fail-on-error cargo fmt --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML} --all
    ''']
