#
# Copyright 2025 Tabs Data Inc.
#

[tasks.__os__lock_rs_macros]
plugin = "td-task-tracker"
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    cd "${PROJECT_RS_TD_MACROS_FOLDER}"

    debug "ðŸš€ cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "ðŸš€ cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1

    debug "ðŸš€ cargo update --verbose -p hyper --precise 1.7.0"
    exit_code = exec --get-exit-code cargo update --verbose -p hyper --precise 1.7.0
    ''']


[tasks.__os__lock_rs_modules]
plugin = "td-task-tracker"
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    cd "${PROJECT_RS_TD_TABSDATA_FOLDER}"

    debug "ðŸš€ cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "ðŸš€ cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1

    debug "ðŸš€ cargo update --verbose -p hyper --precise 1.7.0"
    exit_code = exec --get-exit-code cargo update --verbose -p hyper --precise 1.7.0
    ''']

[tasks.__os__lock_rs_expansions]
plugin = "td-task-tracker"
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    cd "${PROJECT_RS_TY_EXPANSIONS_FOLDER}"

    debug "ðŸš€ cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "ðŸš€ cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1

    debug "ðŸš€ cargo update --verbose -p hyper --precise 1.7.0"
    exit_code = exec --get-exit-code cargo update --verbose -p hyper --precise 1.7.0
    ''']
