#
# Copyright 2025 Tabs Data Inc.
#

[tasks.__os__outdated_rs_macros]
plugin = "td-task-tracker"
category = "05 - Inspect"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML}"
    exec --fail-on-error ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML}
    ''']

[tasks.__os__outdated_rs_modules]
plugin = "td-task-tracker"
category = "05 - Inspect"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_TABSDATA_CARGO_TOML}"
    exec --fail-on-error ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_TABSDATA_CARGO_TOML}
    ''']

[tasks.__os__outdated_rs_expansions]
plugin = "td-task-tracker"
category = "05 - Inspect"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    debug "ðŸš€ cargo upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML}"
    exec --fail-on-error cargo upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML}
    ''']