#
# Copyright 2025 Tabs Data Inc.
#

[tasks.__os__wheels_py]
plugin = "td-task-tracker"
category = "10 - Bundle"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/make-os/libraries/log.ds

    cd "${TESTS_PY_TD_TABSDATA_FOLDER}"

    td_wheels_flavour = get_env TD_WHEELS_FLAVOUR

    exec --fail-on-error python ${WHEELS_SCRIPT} ${td-profile} ${td_wheels_flavour}
    ''']
