#
# Copyright 2024 Tabs Data Inc.
#

[advisories]

# Dependnecies with these advisories are one way or another unmaitained.
# They should be replaced whenever possible, although some of them are transitive dependencies.

# Warning: These ignored advisories are also specified in deny.toml.

ignore = [
    "RUSTSEC-2023-0071",
    "RUSTSEC-2024-0436",
    "RUSTSEC-2025-0075",
    "RUSTSEC-2025-0080",
    "RUSTSEC-2025-0081",
    "RUSTSEC-2025-0090",
    "RUSTSEC-2025-0098",
    "RUSTSEC-2025-0100",
    "RUSTSEC-2025-0120"
]